### ISSUE TITLE
Error cloning GLM

### ISSUE THREAD

**Issue by bonomip** [Threona-Kannard/OpenGL-template#2]
after executing the command "python3 python3 getExternal.py"

Starting clone glm
0it [00:00, ?it/s]
Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --branch=development --progress -- https://github.com/g-truc/glm.git ./include/glm
0it [00:00, ?it/s]

**Comment by Threona-Kannard** [comment]
Hi @bonomip , Thank you for your report about the issue.
The change in the branch name of the "glm" repo caused this issue. I have fixed it.
Now, you can run the "getExternal" script without the issues
